style:
  tag:
    color: cyan # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 3 # column width relative to the terminal window
    min_width: 5 # minimum column width as number of characters
  comment:
    color: blue
    width_percentage: 25
    min_width: 30
  snippet:
    color: white

finder:
  command: fzf # equivalent to the --finder option
  # overrides: --tac # equivalent to the --fzf-overrides option
  # overrides_var: --tac # equivalent to the --fzf-overrides-var option

cheats:
  paths:
    - $XDG_CONFIG_HOME/navi/snippets

# search:
  # tags: git,!checkout # equivalent to the --tag-rules option

shell:
  command: zsh
